//Enumerate Seasons
	const Season = {
		winter: 0,
		spring: 1,
		summer: 2,
		fall: 3
	}

//Map
	const Edge = new Map(document.getElementById("map-edge"), 1,1);
	const Holodrum = new Map(document.getElementById("map-holodrum"), 16,16);
	const Subrosia = new Map(document.getElementById("map-subrosia"), 11,8);

//RegionData
	const Region = {
		AncientRuins: new RegionData("Ancient Ruins", [0,1,2, 16,17,18, 33,34], Season.spring),
		TarmRuins: new RegionData ("Tarm Ruins", [32, 48,49,50, 64,65,66,67, 80,81,82,83, 99], Season.fall),
		NorthernPeak: new RegionData ("Northern Peak", [3, 19, 35], Season.winter),
		NorthernPeakAccess: new RegionData ("Northern Peak Access", [51,52, 68], Season.winter),
		TempleRemains: new RegionData ("Temple Remains", [4,5,6,7, 20,21,22,23, 36,37,38,39, 53,54,55], Season.winter),
		GoronMountain: new RegionData ("Goron Mountain", [8,9,10, 24,25,26, 40,41,42, 56,57,58], Season.winter),
		MtCucco: new RegionData ("Mt. Cucco", [11,12,13,14,15, 27,28,29,30,31, 43,44,45,46,47, 59,60,61], Season.summer),
		SpoolSwamp: new RegionData ("Spool Swamp", [96,97,98, 112,113,114,115, 128,129,130,131, 144,145,146, 160,161,162, 176,177,178, 192,193,194], Season.fall),
		HolodrumPlain: new RegionData ("Holodrum Plain", [69, 84,85, 100,101,102,103,104, 116,117,118,119,120, 132,133,134,135,136, 147,148,149, 163,164,165, 179,180,181], Season.spring),
		SunkenCity: new RegionData ("Sunken City", [62,63, 77,78,79, 93,94,95, 109,110,111], Season.summer),
		EyeglassLake: new RegionData ("Eyeglass Lake", [136,137,138, 150,151,152,153,154, 166,167,168,169,170, 182,183,184,185,186], Season.winter),
		EasternSuburbs: new RegionData ("Eastern Suburbs", [124, 139,140,143, 155,156,157,159, 171,172,173,174,175, 187,188, 202,203,204, 218,219, 234,235], Season.fall),
		WoodsOfWinter: new RegionData ("Woods of Winter", [125,126,127, 141,142, 158], Season.summer),
		WesternCoast: new RegionData ("Western Coast", [195,196, 208,209,210,211,212,213, 224,225,226,227,228,229, 240,241,242,243,244], Season.winter),
		HoronVillage: new RegionData ("Horon Village", [197,198,199,200,201, 214,215,216,217, 230,231,232,233, 245,246,247,248,249], Season.summer),
		SamasaDesert: new RegionData ("Samasa Desert", [189,190,191, 205,206,207, 220,221,222,223, 236,237,238,239, 250,251,252,253,254,255], Season.summer),
		NatzuRegion: new RegionData ("Natzu Region", [70,71,72,73,74,75,76, 86,87,88,89,90, 105,106, 121,122], -1),
		MoblinsKeep: new RegionData ("Moblin's Keep", [91,92, 107,108, 123], 0)
	}

//EntranceData
	const Entrances_Holodrum = {
		AncientRuins: [
			new EntranceData("Dungeon 6 (Ancient Ruins)", EntranceData.type.single, 64, 48),
			new EntranceData("Old Man (Give)", EntranceData.type.generic, 448, 16),
			new EntranceData("Wooden Basement", EntranceData.type.single, 16, 224),
		],
		TarmRuins: [
			new EntranceData("Great Fairy", EntranceData.type.generic, 224, 400),
			new EntranceData("Helpful Scrub's Cave", EntranceData.type.single, 608, 528),
			new EntranceData("Music-Loving Scrub's Cave", EntranceData.type.single, 256, 720),
		],
		NorthernPeak: [
			new EntranceData("Onox's Castle", EntranceData.type.single, 552, 48),
		],
		TempleRemains: [
			new EntranceData("Lava-Filled Cave", EntranceData.type.single, 864, 128),
			new EntranceData("Temple Ascent - Lower", EntranceData.type.connector, 1088, 128),
			new EntranceData("Temple Ascent - Upper", EntranceData.type.connector, 1168, 16),
			new EntranceData("Bastion - L", EntranceData.type.connector, 1008, 16),
			new EntranceData("Bastion - R", EntranceData.type.connector, 1056, 16),
			new EntranceData("Portal (Temple Remains Lower)", EntranceData.type.portal, 832, 288),
			new EntranceData("Portal (Temple Remains Upper)", EntranceData.type.special, 752, 32),
		],
		GoronMountain: [
			new EntranceData("Goron Ascent A - Lower", EntranceData.type.connector, 1552, 272),
			new EntranceData("Goron Ascent A - Upper", EntranceData.type.connector, 1552, 208),
			new EntranceData("Goron Ascent B - Lower", EntranceData.type.connector, 1568, 128),
			new EntranceData("Goron Ascent B - Upper", EntranceData.type.connector, 1536, 32),
			new EntranceData("Gorons' Cave - Lower", EntranceData.type.connector, 1456, 400),
			new EntranceData("Gorons' Cave - Middle", EntranceData.type.connector, 1328, 272),
			new EntranceData("Gorons' Cave - Upper", EntranceData.type.connector, 1392, 144),
			new EntranceData("Lone Goron's Cave", EntranceData.type.single, 1472, 160),
			new EntranceData("Old Man", EntranceData.type.generic, 1312, 336),
			new EntranceData("Small Pot Cave", EntranceData.type.single, 1536, 128),
		],
		MtCucco: [
			new EntranceData("Dungeon 4 (Dancing Dragon Dungeon)", EntranceData.type.single, 2128, 144),
			new EntranceData("Floating Platform Cave", EntranceData.type.single, 2512, 176),
			new EntranceData("Great Fairy", EntranceData.type.generic, 2272, 144),
			new EntranceData("Mushroom Cave", EntranceData.type.single, 1872, 160),
			new EntranceData("Mt. Cucco Portal", EntranceData.type.portal, 2304, 208),
			new EntranceData("Pyramid Jewel Cave", EntranceData.type.single, 2208, 144),
			new EntranceData("Cucco Ascent W - Lower", EntranceData.type.connector, 1936, 144),
			new EntranceData("Cucco Ascent W - Upper", EntranceData.type.connector, 1888, 32),
			new EntranceData("Cucco Ascent E - Lower", EntranceData.type.connector, 2480, 80),
			new EntranceData("Cucco Ascent E - Upper", EntranceData.type.connector, 2480, 16),
			new EntranceData("Passage to Sunken City", EntranceData.type.connector, 2176, 480),
		],
		SpoolSwamp: [
			new EntranceData("Dungeon 3 (Poison Moth's Lair)", EntranceData.type.single, 80, 800),
			new EntranceData("Floodgate Keeper's House", EntranceData.type.single, 384, 816),
			new EntranceData("Floodgate Passage - L", EntranceData.type.connector, 16, 800),
			new EntranceData("Floodgate Passage - R", EntranceData.type.connector, 432, 800),
			new EntranceData("Spool Swamp Portal", EntranceData.type.portal, 80, 1456),
			new EntranceData("Square Jewel Cave", EntranceData.type.single, 432, 1536),
		],
		HolodrumPlain: [
			new EntranceData("Blaino's Gym", EntranceData.type.single, 1376, 944),
			new EntranceData("Flooded Cave (West)", EntranceData.type.single, 512, 1408, "Octo Ring"),
			new EntranceData("Flooded Cave (East)", EntranceData.type.single, 1136, 1072, "Quicksand Ring"),
			new EntranceData("Old Man (Give)", EntranceData.type.single, 1040, 848, "Atop the plateau"),
			new EntranceData("Mrs Ruul's House", EntranceData.type.single, 512, 1344),
			new EntranceData("Old Man (Take)", EntranceData.type.generic, 736, 1360),
			new EntranceData("Round Jewel Guardian", EntranceData.type.single, 928, 1424),
		],
		SunkenCity: [
			new EntranceData("Flooded Cave", EntranceData.type.single, 2432, 528),
			new EntranceData("Ingo's House", EntranceData.type.single, 2096, 528),
			new EntranceData("Potion Shop", EntranceData.type.single, 2304, 704),
			new EntranceData("Man's House", EntranceData.type.single, 2112, 816),
			new EntranceData("Master Diver's House", EntranceData.type.single, 2176, 704),
			new EntranceData("Moblins' Hideout", EntranceData.type.single, 2512, 848),
			new EntranceData("Woman's House", EntranceData.type.single, 2512, 464),
			new EntranceData("Passage to Mt. Cucco", EntranceData.type.connector, 2160, 528),
			new EntranceData("Passage to Woods of Winter", EntranceData.type.connector, 2336, 864),
			new EntranceData("Sunken Falls - Master Diver's Test", EntranceData.type.single, 2264, 336),
			new EntranceData("Sunken Falls - Master Diver's Cave", EntranceData.type.single, 2320, 352),
		],
		NorthHoron: [
			new EntranceData("Dungeon 1 (Gnarled Root)", EntranceData.type.single, 1024, 1216),
			new EntranceData("Impa's Refuge", EntranceData.type.single, 976, 1424),
			new EntranceData("Malon's House", EntranceData.type.single, 1328, 1040),
			new EntranceData("Old Man (Give)", EntranceData.type.generic, 1168, 1184),
			new EntranceData("Red Ring Guardian", EntranceData.type.single, 1072, 1312),
		],   
		EyeglassLake: [
			new EntranceData("Booby Trapped Cave", EntranceData.type.single, 1712, 1328),
			new EntranceData("Dungeon 5 (Unicorn's Cave)", EntranceData.type.single, 1680, 1056),
			new EntranceData("Lakebed Bomb Cave", EntranceData.type.single, 1248, 1328),
			new EntranceData("Eyeglass Lake Portal", EntranceData.type.portal, 1472, 1440),
			new EntranceData("Eastern Suburbs Portal", EntranceData.type.portal, 1648, 1200),
		],
		EasternSuburbs: [
			new EntranceData("Magnetic Glove Cave", EntranceData.type.single, 1936, 1552),
			new EntranceData("Windmill Cave - Lower", EntranceData.type.connector, 1680, 1808),
			new EntranceData("Windmill Cave - Middle", EntranceData.type.connector, 1712, 1792),
			new EntranceData("Windmill Cave - Upper", EntranceData.type.connector, 1680, 1760),
			new EntranceData("Old Man (Take)", EntranceData.type.generic, 2432, 1072),
		],
		WoodsOfWinter: [
			new EntranceData("Big Cave", EntranceData.type.single, 2112, 912),
			new EntranceData("Dungeon 2 (Snake's Remains) - Front", EntranceData.type.connector, 2144, 1056),
			new EntranceData("Dungeon 2 (Snake's Remains) - Middle", EntranceData.type.connector, 2208, 1040),
			new EntranceData("Dungeon 2b", EntranceData.type.single, 2272, 1040),
			new EntranceData("Holly's House - Chimney", EntranceData.type.connector, 2512, 928),
			new EntranceData("Holly's House - Front Door", EntranceData.type.connector, 2512, 960),
			new EntranceData("Magnetic Glove Cave", EntranceData.type.single, 2368, 1088),
			new EntranceData("Small Fairy Cave", EntranceData.type.single, 2288, 1088),
			new EntranceData("Passage from Sunken City", EntranceData.type.connector, 2256, 912),
		],
		Graveyard: [
			new EntranceData("Dungeon 7 (Ancient Crypt)", EntranceData.type.single, 64, 1712),
			new EntranceData("Graveyard Secret", EntranceData.type.single, 64, 1808),
			new EntranceData("Graveyard/Western Shore - Graveyard Passage - Lower", EntranceData.type.connector, 256, 1920),
			new EntranceData("Graveyard/Western Shore - Graveyard Passage - Upper", EntranceData.type.connector, 272, 1840),
		],
		WesternCoast: [
			new EntranceData("Great Fairy", EntranceData.type.generic, 576, 1664),
			new EntranceData("Hero's Cave - Dropdown", EntranceData.type.connector, 752, 1744),
			new EntranceData("Hero's Cave - Entrance", EntranceData.type.connector, 704, 1744),
			new EntranceData("Shore House - Main", EntranceData.type.connector, 384, 1696),
			new EntranceData("Shore House - Shed", EntranceData.type.connector, 416, 1680),
			new EntranceData("Pirate Ship (Docked)", EntranceData.type.single, 416, 1888),
			new EntranceData("Old Man", EntranceData.type.generic, 352, 1680),
		],
		HoronVillage: [
			new EntranceData("Advance Shop", EntranceData.type.single, 816, 1552),
			new EntranceData("Bipin & Blossom's House - L", EntranceData.type.connector, 1024, 1952),
			new EntranceData("Bipin & Blossom's House - R", EntranceData.type.connector, 1056, 1952),
			new EntranceData("Clock Shop", EntranceData.type.single, 1168, 1728),
			new EntranceData("Clock Shop Basement", EntranceData.type.single, 1184, 1680),
			new EntranceData("Know-It-All Birds' Hut", EntranceData.type.single, 864, 1552),
			new EntranceData("Mako Tree", EntranceData.type.single, 1536, 1576),
			new EntranceData("Mayor Ruul's House", EntranceData.type.single, 1344, 1600),
			new EntranceData("Mr. Left's House - Main", EntranceData.type.connector, 1488, 1968),
			new EntranceData("Mr. Left's House - Shed", EntranceData.type.connector, 1520, 1952),
			new EntranceData("Old Man", EntranceData.type.generic, 1472, 2016),
			new EntranceData("Horon Village Portal", EntranceData.type.special, 1168, 1968),
			new EntranceData("Vasu Jewelers", EntranceData.type.single, 1360, 1856),
			new EntranceData("Village Shop", EntranceData.type.single, 1040, 1856),
		],
		SamasaDesert: [
			new EntranceData("Desert Cave", EntranceData.type.single, 2016, 1680),
			new EntranceData("Great Fairy", EntranceData.type.generic, 2480, 1424),
			new EntranceData("Pirate Ship (Beached)", EntranceData.type.single, 2320, 1872),
			new EntranceData("Desert Passage - Entrance", EntranceData.type.connector, 2168, 1992),
			new EntranceData("Desert Passage - Exit", EntranceData.type.connector, 2496, 1968),
		],
		NatzuPrairie: [
			new EntranceData("Small Platform Cave", EntranceData.type.single, 1552, 528),
			new EntranceData("Great Fairy", EntranceData.type.generic, 1152, 688),
			new EntranceData("Seed-Loving Scrub", EntranceData.type.single, 1568, 960),
		],
		NatzuRiver: [
			new EntranceData("Small Platform Cave", EntranceData.type.single, 1552, 528),
			new EntranceData("Great Fairy", EntranceData.type.generic, 1152, 688),
			new EntranceData("Seed-Loving Scrub", EntranceData.type.single, 1568, 960),
		],
		NatzuWasteland: [
			new EntranceData("Small Platform Cave", EntranceData.type.single, 1552, 528),
			new EntranceData("Great Fairy", EntranceData.type.generic, 1152, 688),
			new EntranceData("Seed-Loving Scrub", EntranceData.type.single, 1568, 960),
		],
		MoblinsKeep: [
			new EntranceData("Moblin's Fortress - L", EntranceData.type.connector, 1808, 688),
			new EntranceData("Moblin's Fortress - R", EntranceData.type.connector, 1840, 688),
		],
	}

	const Entrances_Subrosia = {
		SubrosianVillage: [
			new EntranceData("Gasha Seed House", EntranceData.type.single, 688, 576),
			new EntranceData("Locked Passage - L", EntranceData.type.connector, 848, 448),
			new EntranceData("Locked Passage - R", EntranceData.type.connector, 896, 448),
			new EntranceData("Portal (Subrosian Market)", EntranceData.type.portal, 1152, 672),
			new EntranceData("Subrosian Chef's House", EntranceData.type.single, 352, 304),
			new EntranceData("Subrosian's House", EntranceData.type.single, 608, 320),
			new EntranceData("Subrosian Market", EntranceData.type.single, 840, 576),
			new EntranceData("Subrosian Smithy", EntranceData.type.single, 576, 448),
		],
		SubrosianVolcanoes: [
			new EntranceData("Big Empty Cave", EntranceData.type.single, 752, 96),
			new EntranceData("Dancing Game", EntranceData.type.single, 704, 288),
			new EntranceData("Dungeon 8 (Sword & Shield Maze)", EntranceData.type.single, 48, 32),
			new EntranceData("Locked Cave", EntranceData.type.generic, 448, 208),
			new EntranceData("Portal (Dancing Game)", EntranceData.type.portal, 864, 32),
			new EntranceData("Portal (Destructive Volcano)", EntranceData.type.portal, 592, 160),
			new EntranceData("Portal (Dungeon 8)", EntranceData.type.portal, 32, 304),
			new EntranceData("Small Chest Cave", EntranceData.type.generic, 176, 176),
			new EntranceData("Remains Volcano", EntranceData.type.single, 592, 96),
		],
		SubrosianWilds: [
			new EntranceData("House of Pirates - L", EntranceData.type.connector, 352, 944),
			new EntranceData("House of Pirates - U", EntranceData.type.connector, 368, 976),
			new EntranceData("Pirate ship (Beached)", EntranceData.type.single, 752, 928),
			new EntranceData("Portal (House of Pirates)", EntranceData.type.portal, 384, 928),
			new EntranceData("Portal (Small Volcanoes)", EntranceData.type.portal, 528, 736),
			new EntranceData("Strange Brothers' House - L", EntranceData.type.connector, 288, 672),
			new EntranceData("Strange Brothers' House - R", EntranceData.type.connector, 336, 688),
		],
		TempleofSeasons: [
			new EntranceData("Main Temple", EntranceData.type.single, 1512, 64),
			new EntranceData("Tower of Fall", EntranceData.type.single, 1648, 32),
			new EntranceData("Tower of Spring", EntranceData.type.single, 1328, 320),
			new EntranceData("Tower of Spring Passage - L", EntranceData.type.connector, 704, 736),
			new EntranceData("Tower of Spring Passage - R", EntranceData.type.connector, 1360, 336),
			new EntranceData("Tower of Summer", EntranceData.type.single, 1328, 80),
			new EntranceData("Tower of Winter", EntranceData.type.connector, 1712, 320),
		],
		SubrosianVillage: [
			new EntranceData("Subrosian Ascent - L", EntranceData.type.connector, 1312, 720),
			new EntranceData("Subrosian Ascent - U", EntranceData.type.connector, 1360, 672),
			new EntranceData("Great Furnace", EntranceData.type.single, 1520, 608),
			new EntranceData("Sign-Loving Subrosian's House", EntranceData.type.single, 1664, 672),
			new EntranceData("Portal (Great Furnace)", EntranceData.type.portal, 1664, 560),
		],
	}

//Key locations
	const KeyLocations = {
		Dungeons: [
			"Dungeon 0 - Hero's Cave",
			"Dungeon 1 - Gnarled Root",
			"Dungeon 2 - Snake's Remains",
			"Dungeon 3 - Poison Moth's Lair",
			"Dungeon 4 - Dancing Dragon Dungeon",
			"Dungeon 5 - Unicorn's Cave",
			"Dungeon 6 - Ancient Ruins",
			"Dungeon 7 - Explorer's Crypt",
			"Dungeon 8 - Sword & Shield Maze",
		],
		Events: [
			"Floodgate Keeper's House",
			"Great Furnace",
			"Moblin's Keep",
			"House of Pirates",
			"Red Ring Guardian",
			"Subrosian Smithy",
		],
		Shops: [
			"Advance Shop",
			"Horon Village Shop",
			"Subrosian Market",
		],
		AreaAccess: [
			"Dancing Dragon Keyhole",
			"Eastern Suburbs",
			"Floodgate Keyhole",
			"Goron Mountain",
			"Graveyard",
			"Mt. Cucco",
			"Sunken City",
			"Tarm Ruins",
			"Temple Remains",
			"Western Coast",
			"Woods of Winter (North)",
			"Woods of Winter (Snake's Remains)",
			"Subrosia (N)",
			"Subrosia (NW)",
			"Subrosia (NE)",
			"Subrosia (S)",
			"Subrosia (SW)",
			"Subrosia (SE)",
		],
		ComplexConnectors: [
			"Goron City (Upper)",
			"Goron City (Middle)",
			"Goron City (Lower)",
			"Windmill (Upper)",
			"Windmill (Middle)",
			"Windmill (Lower)",
		],
		Checks_Bombs: [
			"Dungeon 2 (Basement)",
			"Mayor Ruul's House",
			"Mr. Left's House",
			"House on the Western Coast",
			"Subrosian Volcano",
		],
		Checks_PowerBracelet: [
			"Tower of Summer",
		],
		Checks_RocsFeatherAndCape: [
			"Mt. Cucco East Ascent",
			"Mt. Cucco West Ascent",
			"Graveyard Passage",
			"Horon Village Portal",
			"Lava-Flooded Cave",
			"Tower of Fall",
			"Tower of Spring",
			"Tower of Spring Passage",
			"Tower of Winter",
		],
		Checks_ZorasFlippers: [
			"Flooded Cave (1)",
			"Flooded Cave (2)",
			"Flooded Cave (3)",
			"Flooded Cave (4)",
			"Underwater Passage",
			"Underwater Cave",
			"Floodgate Passage",
			"Sunken City passage to Woods of Winter",
		],
		Checks_MagneticGlove: [
			"Magnetic Glove Cave (1)",
			"Magnetic Glove Cave (2)",
			"Temple Remains Ascent",
		]
		
	}
